name: LINE通知スクリプト

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日00:00 UTC（日本時間9:00）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Pythonをセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 依存パッケージをインストール
      run: pip install -r requirements.txt

    - name: スクリプトを実行
      env:
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        TO_USER_ID: ${{ secrets.TO_USER_ID }}
      run: python main.py
